replicaCount: 2

image:
  repository: nginx
  tag: "does-not-exist"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

app:
  environment: base

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
